apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: {{ .Values.namespace }}
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: "{{ .Values.adminer.image }}"
          ports:
            - containerPort: {{ .Values.service.adminerPort }}
