apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.adminerPort }}
      targetPort: 8080
  selector:
    app: adminer
